"""Persistent deterministic simulation. No model, subprocess, network, or live notes."""

import fcntl
import hashlib
import json
import os
import tempfile
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Protocol

from hearth.artifacts import MAX_ARTIFACT, sync_directory
from hearth.models import Refused, identifier, microdollars


@dataclass(frozen=True)
class Evidence:
    status: str
    output: str | None = None
    cost: int | None = None


class Runtime(Protocol):
    def start(self, run_id: str, instruction: str) -> None: ...
    def inspect(self, run_id: str) -> Evidence: ...
    def stop(self, run_id: str) -> None: ...


class MockRuntime:
    """An explicit test adapter with durable evidence across application restarts.

    A held run stays running until stop is requested. Other scenarios finish during
    start. Instructions are recorded by digest only; summaries use synthetic notes.
    """

    def __init__(self, root: Path, *, scenario: str = "success"):
        if scenario not in {"success", "hold", "failure", "unknown_usage"}:
            raise ValueError("Unknown mock scenario")
        self.root = root
        self.scenario = scenario
        root.mkdir(parents=True, exist_ok=True)

    def _path(self, run_id: str) -> Path:
        identifier(run_id)
        return self.root / (run_id + ".json")

    def _write(self, path: Path, value: dict) -> None:
        fd, temporary = tempfile.mkstemp(prefix=".evidence-", dir=self.root)
        try:
            with os.fdopen(fd, "w") as file:
                json.dump(value, file)
                file.flush()
                os.fsync(file.fileno())
            os.replace(temporary, path)
            sync_directory(self.root)
        finally:
            Path(temporary).unlink(missing_ok=True)

    def start(self, run_id: str, instruction: str) -> None:
        path = self._path(run_id)
        digest = hashlib.sha256(instruction.encode()).hexdigest()
        with (self.root / ".runtime.lock").open("a") as lock:
            fcntl.flock(lock, fcntl.LOCK_EX)
            if path.exists():
                try:
                    with path.open("rb") as file:
                        raw = file.read(MAX_ARTIFACT + 1)
                    if len(raw) > MAX_ARTIFACT:
                        raise ValueError("oversized evidence")
                    previous = json.loads(raw)
                except ValueError, OSError:
                    raise Refused("runtime_evidence_corrupt") from None
                if not isinstance(previous, dict):
                    raise Refused("runtime_evidence_corrupt")
                if previous.get("instruction_digest") != digest:
                    raise Refused("runtime_identity_conflict")
                return
            output = (
                "# Daily summary — simulation\n\n"
                "Generated by a deterministic mock from synthetic notes. No model was called.\n\n"
                "- Completed: drafted the Hearth foundation.\n"
                "- Verified: task submission survives retries.\n"
                "- Next: exercise cancellation and recovery.\n"
            )
            evidence = Evidence("succeeded", output, 2_000)
            if self.scenario == "hold":
                evidence = Evidence("running")
            elif self.scenario == "failure":
                evidence = Evidence("failed", cost=1_000)
            elif self.scenario == "unknown_usage":
                evidence = Evidence("succeeded", output, None)
            self._write(
                path,
                {"instruction_digest": digest, "evidence": asdict(evidence), "simulated": True},
            )

    def inspect(self, run_id: str) -> Evidence:
        path = self._path(run_id)
        try:
            with path.open("rb") as file:
                raw = file.read(MAX_ARTIFACT + 1)
            if len(raw) > MAX_ARTIFACT:
                return Evidence("unknown")
            document = json.loads(raw)
            if not isinstance(document, dict) or document.get("simulated") is not True:
                return Evidence("unknown")
            evidence = Evidence(**document["evidence"])
            if evidence.status not in {"running", "succeeded", "failed", "cancelled"}:
                return Evidence("unknown")
            if evidence.cost is not None:
                microdollars(evidence.cost)
            if evidence.output is not None and (
                not isinstance(evidence.output, str) or len(evidence.output.encode()) > MAX_ARTIFACT
            ):
                return Evidence("unknown")
            if evidence.status == "succeeded" and (
                not isinstance(evidence.output, str) or not evidence.output.strip()
            ):
                return Evidence("unknown")
            return evidence
        except FileNotFoundError:
            return Evidence("absent")
        except OSError, ValueError, KeyError, TypeError:
            return Evidence("unknown")

    def stop(self, run_id: str) -> None:
        path = self._path(run_id)
        with (self.root / ".runtime.lock").open("a") as lock:
            fcntl.flock(lock, fcntl.LOCK_EX)
            if self.inspect(run_id).status != "running":
                return
            document = json.loads(path.read_text())
            document["evidence"] = asdict(Evidence("cancelled", cost=1_000))
            self._write(path, document)
